EXEC INSERT_AWARD'Best Actor', 'Individual'
EXEC INSERT_AWARD'Best Actress', 'Individual'
EXEC INSERT_AWARD'Best Original Screenplay', 'Film'
EXEC INSERT_AWARD'Best Picture', 'Film'
EXEC INSERT_AWARD'Best Foreign Film', 'Film'
