EXEC NEW_PROD 'Movie', 'Sci-Fi', 'R', 'The Terminator'
EXEC NEW_PROD 'Movie', 'Sci-Fi', 'PG-13', 'Ready Player One'
EXEC NEW_PROD 'Movie', 'Horror', 'PG-13', 'Get Out'
EXEC NEW_PROD 'Movie', 'Action', 'PG-13', 'Black Widow'
EXEC NEW_PROD 'TV-Show', 'Drama', 'PG-13', 'Gossip Girls'
EXEC NEW_PROD 'Movie', 'Horror', 'PG-13', 'A Quiet Place'