
-- SELECT * FROM INFO_330_Proj_09.dbo.PROFESSIONAL
-- SELECT * FROM AWARD
-- SELECT * FROM PROFESSIONAL_NOMINATION

EXEC INSERT_PROFESSIONAL_NOMINATIONS 'Best Actor', 'Arnold', 'Schwarzenegger', '1947-07-30', 0
EXEC INSERT_PROFESSIONAL_NOMINATIONS 'Best Actor', 'Scarlett', 'Johansson', '1984-11-22', 0

